INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040620', 'ALONSO' ,'FLORES', 'AIXCHELL CAMILA','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040038', 'ALVAREZ' ,'ZEPEDA', 'NALLELY ALITZEL','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040621', 'CABALLERO' ,'VARGAS', 'JOSE ROBERTO','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040006', 'CHICO' ,'VALDEZ', 'ILSE MARIEL','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040508', 'CONTRERAS' ,'ROCHA', 'ESMERALDA','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13048005', 'CRUZ' ,'MORENO', 'ALONDRA BRISEIDA','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040553', 'DE LA FUENTE' ,'OLIVA', 'ZAIRA SOFIA','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040253', 'GARCIA' ,'MORFIN', 'PAUL MARTIN','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040472', 'GARCIA' ,'QUINTANA', 'DEMIAN VALENTIN','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040558', 'GARCIA' ,'VILLAGRAN', 'JOSE IAN','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040217', 'GIL' ,'FELIX', 'ABRAHAM','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040221', 'GONZALEZ' ,'MOJICA', 'XIOMARA YAEL','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040154', 'GUZMAN' ,'FERNANDEZ', 'KAREN NAOMI','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040292', 'HERNANDEZ' ,'SEGURA', 'GABRIELA','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040447', 'LIMON' ,'BAUTISTA', 'ARMANDO','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040564', 'LOPEZ' ,'BECERRA', 'JESUS ALBERTO','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040479', 'LOPEZ' ,'MIGUEL', 'HUGO','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040056', 'MACIAS' ,'CABALLERO', 'LISBETH','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040414', 'MARTINEZ' ,'CERVANTES', 'MIROSLAVA','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040481', 'MARTINEZ' ,'GALLEGOS', 'LISEK','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13047004', 'MORENO' ,'MORA', 'MONSERRAT','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040194', 'NAVARRETE' ,'GONZALEZ', 'ZELTZIN DONAJI','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13049010', 'ORTIZ' ,'ARREDONDO', 'JOHAN ALEXIS','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040132', 'RAMIREZ' ,'RAMIREZ', 'ARTURO','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040423', 'RODRIGUEZ' ,'ARIAS', 'JOAHAN','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040613', 'RODRIGUEZ' ,'GARCIA', 'CEDRIC DE JESUS','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040346', 'SANCHEZ' ,'CHAVEZ', 'JOHANA ELIZABETH','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040542', 'VENEGAS' ,'RAMIREZ', 'GIOVANNI JOSUE','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040207', 'VERGARA' ,'MENDOZA', 'MONICA IVETTE','412');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040174', 'ZAMARRIPA' ,'ALMERIA', 'ANDRES DANIEL','412');