INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040544', 'ANGELES' ,'LEOS', 'EDUARDO DEMIAN','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040210', 'BAUTISTA' ,'ROMAN', 'ASTRID JAQUELINE','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13047003', 'CABRERA' ,'GUZMAN', 'LUIS ARTURO','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040143', 'CABRERA' ,'PORTILLA', 'ISRAEL','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13048003', 'CASTILLO' ,'OLVERA', 'YENY FERNANDA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040801', 'DELGADILLO' ,'ROY OCOTLA', 'ARELI','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040400', 'DIAZ' ,'MARTINEZ', 'JESSICA GIOVAN','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040403', 'FEREGRINO' ,'GUTIERREZ', 'MONSERRAT','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040118', 'GOMEZ' ,'SANTANA', 'LISA PAMELA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13049020', 'GONZALEZ' ,'ORDAZ', 'KEVIN EMMANUEL','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040052', 'GUERRERO' ,'LOPEZ', 'HILDA FERNANDA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040329', 'GUTIERREZ' ,'MENDOZA', 'EDUARDO ANTONIO','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040225', 'IBARRA' ,'MORENO', 'PEDRO','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13049090', 'LANDIN' ,'HERNANDEZ', 'SANDRA PAOLA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040634', 'LAZARO' ,'LAZARO', 'HECTOR ULISES','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040016', 'LEON' ,'LAGUNA', 'LUIS MANUEL','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040082', 'LOZANO' ,'VITE', 'IRIS PAOLA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040375', 'MOLINA' ,'JASSO', 'JOSE','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040062', 'MORENO' ,'MOGOYAN', 'MARIANA ALEJANDRA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040525', 'ORDAZ' ,'PEREZ', 'ABRIL ARANZA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040610', 'PERALTA' ,'AYALA', 'SEBASTIAN JAIR','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040489', 'PEREZ' ,'CHANTES', 'MARIANA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040092', 'RAMIREZ' ,'VAZQUEZ', 'HORTENCIA ALEJANDRA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040166', 'RAMOS' ,'GONZALEZ', 'MARIA DEL CARMEN','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040422', 'RIVAS' ,'GARCIA', 'ERNESTO','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040310', 'SANCHEZ' ,'PEREZ', 'STEPHANIE BARBARA','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13049023', 'SANCHEZ' ,'VARGAS', 'MARIA DEL ROSARIO','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040202', 'TAPIA' ,'LEDESMA', 'YAMILET ATZIRI','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040501', 'TOSCANO' ,'MEDRANO', 'JESUS','413');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040139', 'VENEGAS' ,'MONTOYA', 'NADIA ELENA','413');