INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040001', 'ACOSTA' ,'BADILLO', 'ALONDRA ALHELI','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040316', 'ANGEL' ,'GOMEZ', 'BRENDA JIMENA','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040175', 'ARRIAGA' ,'SABAS', 'ROMARIO JOSEF','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040354', 'AVILA' ,'PINEDA', 'GUADALUPE GETSEMANI','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13048016', 'BELTRAN' ,'TAPIA', 'CESAR ALEE','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040357', 'CABRERA' ,'LEAL', 'ITZEL GUADALUPE','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040622', 'CABRERA' ,'SANCHEZ', 'MAURICIO AARON','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040319', 'CARREON' ,'FRANCO', 'ALEJANDRO','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040394', 'CEBALLOS' ,'GONZALEZ', 'ANDREA STHEPHANIE','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13049003', 'CRUZ' ,'GALVAN', 'ANGELICA VALERIA','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040218', 'GOMEZ' ,'RAMIREZ', 'RODRIGO','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13046007', 'GUTIERREZ' ,'MARTINEZ', 'NAYELLI ITZEL','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040120', 'HERNANDEZ' ,'REYES', 'HECTOR DANIEL','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040596', 'HIPOLITO' ,'ALVARADO', 'JOSE RICARDO','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13049096', 'JIMENEZ' ,'PACHECO', 'SEBASTIAN','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040637', 'LOPEZ' ,'REYES', 'ROBERT ALEXIS','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040482', 'MARTINEZ' ,'LOPEZ', 'ANA SOFIA','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040393', 'MAYA' ,'YESCAS', 'KAREN','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040601', 'MENDOZA' ,'ROJAS', 'DAVID SALVADOR','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040419', 'NAVARRO' ,'PEÑA', 'RAFAEL ISAAC','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040644', 'ORTIZ' ,'PADILLA', 'MICHELLE','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040569', 'PEREZ' ,'OLIVA', 'OLLIN','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13048042', 'RAMIREZ' ,'GUERRERO', 'PAOLA BEATRIZ','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040341', 'ROBLEDO' ,'ESTRADA', 'MARIANA PAOLA','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040236', 'ROBLES' ,'MORALES', 'FRANCISCO','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13047012', 'RODRIGUEZ' ,'ALVAREZ', 'FERNANDO','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13046004', 'RUBIO' ,'GARCIA', 'KARLA','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040172', 'VARGAS' ,'MARTINEZ', 'BRUNO','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040654', 'VENEGAS' ,'PARRA', 'CARLOS EDUARDO','423');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('13040464', 'YESCAS' ,'ANDRADE', 'MARIA FERNANDA','423');