INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040609', 'AVIÑA' ,'LEON', 'GETZEMANY LESLY','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040229', 'CORONEL' ,'LOPEZ', 'AMEYALLI MONSERRAT','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040380', 'DURAN' ,'CHABLE', 'JHOANA','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040122', 'FERNANDEZ' ,'MONROY', 'DAVID ARTURO','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040012', 'FLORES' ,'PEREZ', 'DANIELA IVONNE','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040014', 'FUENLABRADA' ,'VELAZQUEZ', 'PAULINA','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040128', 'GUEVARA' ,'GONZALEZ', 'CARLOS ENRIQUE','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040307', 'GUTIERREZ' ,'REYES', 'MARIO AXEL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040347', 'HERNANDEZ' ,'GRED', 'MIGUEL KINAM','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040426', 'HERNANDEZ' ,'ISLAS', 'AXEL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040623', 'HERRERA' ,'TORRES', 'FIDEL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040091', 'JIMENEZ' ,'BONILLA', 'BRISA SARAI','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040051', 'JIMENEZ' ,'FERNANDEZ PIDAL', 'ALAN','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040698', 'JUAREZ' ,'HERNANDEZ', 'ATXEL URIEL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040241', 'MAURICIO' ,'ALVAREZ', 'RAUL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040058', 'MERA' ,'PACHECO', 'ITZAYANA','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040667', 'ORTIZ' ,'GALVAN', 'KEVIN','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040400', 'PEREZ' ,'EGUIA', 'DANIELA MAYTE','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040479', 'RANGEL' ,'PANTOJA', 'EVELYN VIRIDIANA','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040180', 'ROCHA' ,'ROSALES', 'ALEJANDRO','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040561', 'RODRIGUEZ' ,'LOYOLA', 'VICTOR MANUEL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040972', 'RODRIGUEZ' ,'RESENDIZ', 'JIMENA','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040990', 'RUEDA' ,'FRANCO', 'HECTOR FANTAGYRO','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040563', 'SALTO' ,'GUTIERREZ', 'ABDEL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040444', 'SANCHEZ' ,'XAVIER', 'XILONEN GUADALUPE','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040976', 'VALAGUEZ' ,'GONZALEZ', 'ABIGAIL','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040332', 'VAZQUEZ' ,'VIEYRA', 'MARIANA','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040967', 'VERA' ,'RICHARD', 'JACQUELINE','611');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040900', 'VERTIZ' ,'CASILLAS', 'FRANCISCO GAEL','611');