INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040112', 'AGUILAR' ,'JALOMA', 'VICTOR MANUEL','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040336', 'ARELLANO' ,'VELASQUEZ', 'CESAR MAURICIO','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040299', 'BAZAN' ,'ROMAN', 'RICARDO','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040194', 'CAUDILLO' ,'RIVERO', 'ALONSO','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040008', 'CRUZ' ,'GIL', 'JOSE MANUEL','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040539', 'DELGADO' ,'REYES', 'ALEJANDRA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040121', 'ELIAS' ,'ELENO', 'MICHELLE','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040691', 'ESCAMILLA' ,'HERNANDEZ', 'ALLAN JAIR','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040088', 'GOMEZ' ,'CARMONA', 'IRMA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040344', 'GONZALEZ' ,'PORTILLO', 'RAUL','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040272', 'HERNANDEZ' ,'MENDEZ', 'MELISSA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040016', 'HERNANDEZ' ,'SANCHEZ', 'HECTOR AXEL','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040353', 'LOPEZ' ,'JUAREZ', 'MARIA FERNANDA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040392', 'LOPEZ' ,'LOPEZ', 'RANDAL EMMANUELLE','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040511', 'MARTINEZ' ,'MEXICANO', 'JAQUELINE EMILIA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040432', 'MARTINEZ' ,'VALLEJO', 'BRENDA LISSET','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040473', 'MARTINEZ' ,'VELAZQUEZ', 'GRECIA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040512', 'MAYA' ,'MANZANO', 'XIMENA LIZETH','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040514', 'MELGAREJO' ,'PEREZ', 'HECTOR DAVID','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040026', 'MENDOZA' ,'SALAZAR', 'VICTOR URIEL','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040206', 'MORENO' ,'LEON', 'MARCO ALAN','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040136', 'NORIEGA' ,'MENDIOLA', 'MARIANA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040178', 'QUINTERO' ,'ZAMACONA', 'ANA KARLA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040216', 'RANGEL' ,'PANTOJA', 'DIANA ALEJANDRA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040673', 'RIVERA' ,'BAZAN', 'MELISSA ISABEL','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040258', 'TORRES' ,'BAUTISTA', 'NIRVANA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040604', 'VILLALOBOS' ,'DAMIAN', 'FABIOLA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040371', 'VILLANUEVA' ,'JAVIER', 'KARLA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040527', 'VILLAVICENCIO' ,'PEREZ', 'MARIA FERNANDA','612');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040184', 'VITTE' ,'SAN JUAN', 'BRUNO','612');