INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040682', 'AGUIRRE' ,'VILLEGAS', 'ARTURO','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040113', 'ALMAGUER' ,'ALBURO', 'JESUS','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040151', 'ALTAMIRANO' ,'MENDOZA', 'ARELI','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040152', 'ARRATIA' ,'FRANCO', 'ANDREA ATALA','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040532', 'BEDOLLA' ,'CARRILLO', 'ALEXIS','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040610', 'BOLAÑOS' ,'PANO', 'ADRIANA','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040116', 'CAMPOS' ,'ACUÑA', 'AXEL ALEJANDRO','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040154', 'CARDENAS' ,'AVALOS', 'MARIA TERESA','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040648', 'CRUZ' ,'RAMIREZ', 'YURITSY POOLET','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040119', 'DIAZ' ,'DIAZ', ' IRAN YESENIA','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040981', 'GRANCIANO' ,'CEDEÑO', 'VALERIA','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040427', 'HERNANDEZ' ,'UGALDE', 'JENNIFER','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040234', 'HERNANDEZ' ,'VELAZQUEZ', 'EMMANUEL ALEJANDRO','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040280', 'MARTINEZ' ,'RAZO', 'FRANCISCO JAVIER','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040555', 'MORALES' ,'CORONA', 'EDGAR MAURICIO','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040099', 'MORALES' ,'GARIBALDI', 'CARLOS','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040629', 'MORALES' ,'SALGADO', 'LEONARDO DANIEL','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040060', 'NAVA' ,'CORTES', 'MARIANA','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040631', 'OSORIO' ,'MONROY', 'SHEILA GRIZEL','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040557', 'PEDRAZA' ,'RUIZ', 'JOSE LUIS','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040361', 'PINEDA' ,'ESCAMILLA', 'ESPERANZA ABIGAIL','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040214', 'RAMIREZ' ,'CARRASCO', 'JORGE ULISES','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040179', 'RAMIREZ' ,'MARTINEZ', 'ERICK DAVID','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040104', 'RIVERA' ,'GOMEZ', 'LIZETH VANESSA','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040480', 'RODRIGUEZ' ,'HERNANDEZ', 'GALA LISSET','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040443', 'RODRIGUEZ' ,'MARTINEZ', 'KAREN ARELY','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040601', 'ROSETE' ,'ISLAS', 'AMIEL JOEL','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040565', 'SOSA' ,'TREJO', 'JOCELYN','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040369', 'TELLEZ' ,'CALZADA', 'MERCEDES','613');
INSERT INTO Alumnos (Folio, Apellido_P, Apellido_M, Nombre, grupo) VALUES ('12040680', 'VELASCO' ,'OCHOA', 'ALEXANDRA ZURIEL','613');