use dev_examen;

/* Seccion 3 ---------------------------------------------------------------------------------------------------------------------------------*/


insert into Materias values ("3003", "3000", "Seccion 3", "images/L7.png", "¿Qué función de la lengua predomina en el texto?", "Poética", "Metalinguística", "Referencial", "Fática");
insert into Materias values ("3004", "3000", "Seccion 3", "images/T2.png", "Relaciona las ideas principales con la parte de la estructura del texto a la que corresponda", "1=B, 2=D, 3=F", "1=D, 2=E, 3=B ", "1=G, 2=C, 3=F", "1=D, 2=F, 3=G");
insert into Materias values ("3005", "3000", "Seccion 3", "images/L8.png", "Señala el tipo de argumento que presenta la madre.", "Descriptivo", "Persuasivo", "Demostrativo", "Analógico");
insert into Materias values ("3006", "3000", "Seccion 3", "images/L9.png", "Señala qué partes del texto argumentativo corresponden a cada párrafo", "Tesis: Párrafo 2    Argumentos: Párrafo 3 y 4   Conclusiones: Parrafo 1","Tesis: Párrafo 3    Argumentos: Párrafo 1 y 2   Conclusiones: Parrafo 4", "Tesis: Párrafo 1 y 4    Argumentos: Párrafo 3    Conclusiones: Parrafo 2", "Tesis: Párrafo 1    Argumentos: Párrafo 2 y 3   Conclusiones: Parrafo 4");
insert into Materias values ("3007", "3000", "Seccion 3", "", "¿Cómo se denomina a la información que se transcribe de manera íntegra a un escrito?", "Resumen","Paráfrasis", "Cita textual", "Comentario");
insert into Materias values ("3008", "3000", "Seccion 3", "", "ES la redacción de un texto o discurso de tal forma que solo contenga sus ideas centrales. El propósito fundamental de éste es alcanzar la comprensión total de un texto, lo que permite recordar fácilmente las ideas principales. La elaboración de éste texto consta de dos fases: lectura de comprensión (lectura y análisis) y producción (redacción) ", "Reseña","Comentario", "Esquema", "Resumen");
insert into Materias values ("3009", "3000", "Seccion 3", "", "¿A qué etapa del proceso de producción de un texto se refiere la siguiente definición?
Consiste en depurar el contenido elaborado, organizar mejor las ideas, simplificar las oraciones, precisar los datos, atender a la puntuación y a la ortografía con el fin de mejorar la redacción. No sólo se pone atención en las palabas o frases sueltas sino también en las ideas o fragmentos extensos para aclarar el texto en sí.", "Revisar","Corregir", "Planear", "Escribir");

insert into Materias values ("3010", "3000", "Seccion 3", "", "Escribe el texto que tenga el propósito comunicativo de expresar un amor no correspondido. ", "Texto 1. Hay un lugar de honor / que te concedo / en la parte más frágil / de mi lado izquierdo / mientras cantas con fuerza, colibrí.","Texto 2. No llores, por Dios, Margarita; no llores, porque tus lágrimas me hacen daño. Voy a alejarme de ti; más yo volveré después de haber conseguido un poco de gloria para mi oscuro nombre.", "Texto 3. Me doy cuenta de que me faltas / y de que te busco entre las gentes, en el ruido, / pero todo es inútil. /  Cuando me quedo solo / solo por todas partes y por ti y por mí.", "Texto 4. A mí me cuesta ser cariñoso, inclusive en la vida amorosa. Siempre doy menos de lo que tengo. Mi estilo de querer es ése, un poco reticente, reservando, el máximo sólo para las grandes ocasiones.");
insert into Materias values ("3011", "3000", "Seccion 3", "", "Determina el inciso en el que se refleja el valor ético del amor al trabajo.", "Estoy cansado. A veces ya no deseo venir, pero pienso en el dinero, me fortalezco y regreso.", "Aquí estoy haciendo un escuela bonita, bonita, bonita… ya verás qué escuela será.", "Pues hombre. Hay que trabajar, ganarse el pan y mirar por los hijos. Es ley de vida.", "Aquí ando, trabajando y sudando como un tonto, sólo esperando a irme de aquí.");
insert into Materias values ("3012", "3000", "Seccion 3", "images/T3", "Relaciona el subgénero literario con la intención comunicativa que lo caracteriza.", "1c, 2b, 3a ", "1c, 2a, 3b", "1b, 2c, 3a", "1b, 2a, 3c");
insert into Materias values ("3013", "3000", "Seccion 3", " ", "Elije la secuencia diálogo-descripción", "– Ahora está soñado. ¿Con quién sueña? ¿lo sabes? –Nadie lo sabe. –Sueña contigo. Y si dejara de soñar, ¿qué sería de ti? ", "Cierto día un rey organizó un gran banquete en el salón principal del palacio. Invitó a todos los hombres más nobles de su reino.", "El caballo herido y jadeante había llegado buscando un espacio verde imposible. Tenía la pierna hincada y con coágulos negros de sangre.", "Una mujer alta, elegante y de ojos verdes se presentó un día en la floristería de Ramón. Ella ordeno: –Media docena de rosas, por favor.");
insert into Materias values ("3014", "3000", "Seccion 3", " ", "El profesor ha solicitado a los alumnos elaborar un ensayo sobre la vulnerabilidad de los adolescentes en el uso de las redes sociales, ¿qué opción contiene información adecuada para dicho ensayo?", "Existen tres categorías de riesgos en las redes sociales. La primera, describe los riesgos de contenido, un ejemplo de este es el denominado “provocador”, el cual los adolescentes lo encuentran en los mensajes de odio. La segunda categoría incluye los riesgos de contacto, están presentes en las opciones de mensajería instantánea y constituyen los medios más populares utilizados para el ciberacoso ya sea a través del chat o la publicación de mensajes. La tercera categoría contiene los riesgos comerciales, un ejemplo de esto es el uso indebido de datos personales.", "En el uso de Internet debe considerarse la impersonalidad de estos medios, su alcance considerable como plataforma ilimitada de comunicación. Pero nadie tiene certeza de que su mensaje sólo lo reciba la persona a quien va dirigido. Se informa que 49% de las y los usuarios de redes sociales en México son jóvenes que no se cuidan, porque la mayoría no cree en los peligros de las redes sociales, ya que piensan que solamente se trata de historias de personas viejas.", "Las redes sociales en Internet son un imán para los jóvenes. En estos sitios, puede crear su propio mundo, a través del que establece relaciones con otros. Padres y educadores no deberían olvidar la existencia de unos “lugares” de ocio que no parecen un fenómeno efímero y que influirán en la educación de sus hijos. A la vez, deben compartir con las autoridades la precaución por la falta de seguridad que puede derivarse de estas web.", "Las redes sociales se han convertido en una herramienta de comunicación buena, bonita y barata para empresas de todos los tamaños. Según el primer estudio a nivel mundial sobre el uso de las Web 2.0, que acaba de publicar McAfee, 75% de las empresas de todo el mundo han adoptado las aplicaciones web como herramienta empresarial por su potencial para generar ingresos. Pero a la vez que se aprecian sus ventajas, poco a poco se va tomando también conciencia de los nuevos  riesgos que entraña su uso en la oficina, fundamentalmente por el aumento de problemas de seguridad y la pérdida de productividad de las plantillas.");
insert into Materias values ("3015", "3000", "Seccion 3", "", "¿A qué tipo de medio corresponden los mensajes de televisión?", "Multimedia", "Icónico verbal", "Audiovisual", "Visual");
insert into Materias values ("3016", "3000", "Seccion 3", "", "Elige un enunciado argumentativo", "El proyecto “Lisistrata” promueve el teatro como un fenómeno que tiene que hablar de las cosas que ocurren en el ámbito social. Esta iniciativa es muy inteligente, pues convoca a que cada quien participe como pueda.", "Aristófanes nació en la época de Pericles, su nacimiento se puede situar en torno al 445 a.C. No parece que militara en ningún partido político, pero participó en las luchas políticas. Es considerado como un autor importante.", "Lisistrata es inteligente, decidida y triunfadora, aunque a veces hostil. Ha convocado a las mujeres a una reunión para asumir una posición frente a la actitud de los hombres. Tiene razón al no estar de acuerdo con ellos.", "Durante el mandato de Pericles se construyó el Partenón, el cual está dedicado a la diosa Atenea protectora de las cosechas y de la sabiduría. Es hija del dios Zeus. Cuenta la mitología que nació de la cabeza de su padre");
insert into Materias values ("3017", "3000", "Seccion 3", "", "¿Qué tipo de argumento es el enunciado “dijo el nutriólogo que abusar del azúcar no es bueno ni para tu estómago ni para tu salud en general”?", "Ejemplo", "CAusa", "Autoridad", "Analógico");
insert into Materias values ("3018", "3000", "Seccion 3", "", "Tipo de palabras que se utilizan en una disciplina específica, con la intención de comunicar información correspondiente a esa área del conocimiento.", "Neologismos", "Tecnicismos", "Barbarismos", "Extranjerismos");
insert into Materias values ("3019", "3000", "Seccion 3", "images/T4.png", "Relaciona el tipo de conector con el párrafo correspondiente.", "Neologismos", "Tecnicismos", "Barbarismos", "Extranjerismos");
